#!/usr/bin/env python3
"""Fetch a real mainnet ledger from Horizon and emit it as a Rust test fixture.

The fixture is self-validating: the script checks that the header hashes to
the published ledger hash, that the reconstructed TransactionResultSet hashes
to the header's txSetResultHash, and that the parent header hashes to the
header's previousLedgerHash. It also computes the expected results Merkle
root independently of the contract, so the Rust tests cross-check both
implementations.

Usage: scripts/fetch_fixture.py [LEDGER_SEQ] > src/fixtures.rs
"""

import base64
import hashlib
import json
import struct
import sys
import urllib.request

HORIZON = "https://horizon.stellar.org"
DEFAULT_LEDGER = 64701890

# Operation types the envelope decoder supports (everything classic except
# RevokeSponsorship); Soroban operations are rejected.
SUPPORTED_OPS = {
    "create_account", "payment", "path_payment_strict_receive", "manage_sell_offer",
    "create_passive_sell_offer", "set_options", "change_trust", "allow_trust",
    "account_merge", "inflation", "manage_data", "bump_sequence", "manage_buy_offer",
    "path_payment_strict_send", "create_claimable_balance", "claim_claimable_balance",
    "begin_sponsoring_future_reserves", "end_sponsoring_future_reserves", "clawback",
    "clawback_claimable_balance", "set_trust_line_flags", "liquidity_pool_deposit",
    "liquidity_pool_withdraw",
}


def get(path):
    with urllib.request.urlopen(HORIZON + path if path.startswith("/") else path) as r:
        return json.load(r)


def paged(path):
    out, url = [], HORIZON + path
    while url:
        page = get(url)
        recs = page["_embedded"]["records"]
        out += recs
        url = page["_links"]["next"]["href"] if len(recs) == 200 else None
    return out


def sha(b):
    return hashlib.sha256(b).digest()


def merkle_root(leaves):
    depth = max(0, (len(leaves) - 1).bit_length())
    zero, level = b"\x00" * 32, list(leaves)
    for _ in range(depth):
        if len(level) % 2:
            level.append(zero)
        level = [sha(b"\x01" + level[i] + level[i + 1]) for i in range(0, len(level), 2)]
        zero = sha(b"\x01" + zero + zero)
    return level[0], depth


def rust_hex(name, data):
    return f'pub const {name}: &str = "{data.hex()}";\n'


def main():
    seq = int(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_LEDGER
    ledger = get(f"/ledgers/{seq}")
    parent = get(f"/ledgers/{seq - 1}")
    header = base64.b64decode(ledger["header_xdr"])
    parent_header = base64.b64decode(parent["header_xdr"])
    assert sha(header).hex() == ledger["hash"], "header hash mismatch"
    assert sha(parent_header) == header[4:36], "parent is not previousLedgerHash"

    txs = paged(f"/ledgers/{seq}/transactions?include_failed=true&order=asc&limit=200")
    results = struct.pack(">I", len(txs)) + b"".join(
        bytes.fromhex(t["hash"]) + base64.b64decode(t["result_xdr"]) for t in txs
    )

    ops = paged(f"/ledgers/{seq}/operations?include_failed=true&order=asc&limit=200")
    op_types = {}
    for op in ops:
        op_types.setdefault(op["transaction_hash"], set()).add(op["type"])

    def pick(envelope_type, predicate):
        for i, t in enumerate(txs):
            env = base64.b64decode(t["envelope_xdr"])
            if struct.unpack(">i", env[:4])[0] == envelope_type and predicate(op_types.get(t["hash"], set())):
                return i, t
        raise SystemExit(f"no envelope of type {envelope_type} matched")

    payment_idx, payment = pick(2, lambda s: s == {"payment"})
    bump_idx, bump = pick(5, lambda s: s and s <= SUPPORTED_OPS)

    leaves = [
        sha(b"\x00" + bytes.fromhex(t["hash"]) + base64.b64decode(t["result_xdr"])[8:12])
        for t in txs
    ]
    root, depth = merkle_root(leaves)

    def code(t):
        return struct.unpack(">i", base64.b64decode(t["result_xdr"])[8:12])[0]

    out = [
        f"// Mainnet ledger {seq} (closed {ledger['closed_at']}, protocol {ledger['protocol_version']}).\n",
        "// Generated by scripts/fetch_fixture.py; do not edit by hand.\n\n",
        f"pub const LEDGER_SEQ: u32 = {seq};\n",
        rust_hex("LEDGER_HASH", sha(header)),
        rust_hex("HEADER_XDR", header),
        rust_hex("PARENT_HEADER_XDR", parent_header),
        rust_hex("RESULTS_XDR", results),
        f"pub const TX_COUNT: u32 = {len(txs)};\n",
        f"pub const RESULTS_DEPTH: u32 = {depth};\n",
        rust_hex("RESULTS_ROOT", root),
        f"pub const PAYMENT_INDEX: u32 = {payment_idx};\n",
        f"pub const PAYMENT_RESULT_CODE: i32 = {code(payment)};\n",
        rust_hex("PAYMENT_TX_HASH", bytes.fromhex(payment["hash"])),
        rust_hex("PAYMENT_ENVELOPE_XDR", base64.b64decode(payment["envelope_xdr"])),
        f"pub const FEE_BUMP_INDEX: u32 = {bump_idx};\n",
        f"pub const FEE_BUMP_RESULT_CODE: i32 = {code(bump)};\n",
        rust_hex("FEE_BUMP_TX_HASH", bytes.fromhex(bump["hash"])),
        rust_hex("FEE_BUMP_ENVELOPE_XDR", base64.b64decode(bump["envelope_xdr"])),
    ]
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
