# Example: Running Grafana Tempo as an OTLP backend for Stellar-K8s distributed tracing
#
# This docker-compose file starts a minimal observability stack:
#   - Grafana Tempo (OTLP gRPC + HTTP receiver, Tempo query API)
#   - Grafana (dashboard UI)
#
# Usage:
#   docker compose -f docs/otlp-collector-example.yaml up -d
#
# Then start the operator with the endpoint configured:
#   OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317 cargo run -- run
#
# Open Grafana at http://localhost:3000 (admin/admin) and import
# docs/tracing-dashboard.json to see your traces.

services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "4317:4317"    # OTLP gRPC receiver (used by stellar-operator)
      - "4318:4318"    # OTLP HTTP receiver (alternative)
      - "3200:3200"    # Tempo query API (used by Grafana)
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    restart: unless-stopped

volumes:
  tempo-data:
  grafana-data:
